version: '3.7'
services:
  dev:
    image: 'devcontainer_local_django:dev'
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - '.:/app/src:z'
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - local/environment
